// <auto-generated />
using Dgii.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Dgii.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260615191241_AddMoreSeedData")]
    partial class AddMoreSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Dgii.Domain.Entities.TaxReceipt", b =>
                {
                    b.Property<string>("NCF")
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<decimal>("Itbis18")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RncCedula")
                        .IsRequired()
                        .HasColumnType("nvarchar(11)");

                    b.HasKey("NCF");

                    b.HasIndex("RncCedula");

                    b.ToTable("TaxReceipts");

                    b.HasData(
                        new
                        {
                            NCF = "E310000000001",
                            Itbis18 = 36.00m,
                            Monto = 200.00m,
                            RncCedula = "98754321012"
                        },
                        new
                        {
                            NCF = "E310000000002",
                            Itbis18 = 180.00m,
                            Monto = 1000.00m,
                            RncCedula = "98754321012"
                        },
                        new
                        {
                            NCF = "E310000000003",
                            Itbis18 = 900.00m,
                            Monto = 5000.00m,
                            RncCedula = "101010101"
                        },
                        new
                        {
                            NCF = "E310000000004",
                            Itbis18 = 270.00m,
                            Monto = 1500.00m,
                            RncCedula = "101010101"
                        },
                        new
                        {
                            NCF = "E310000000005",
                            Itbis18 = 63.00m,
                            Monto = 350.00m,
                            RncCedula = "202020202"
                        },
                        new
                        {
                            NCF = "E310000000006",
                            Itbis18 = 216.00m,
                            Monto = 1200.00m,
                            RncCedula = "404040404"
                        },
                        new
                        {
                            NCF = "E310000000007",
                            Itbis18 = 72.00m,
                            Monto = 400.00m,
                            RncCedula = "606060606"
                        },
                        new
                        {
                            NCF = "E310000000008",
                            Itbis18 = 1800.00m,
                            Monto = 10000.00m,
                            RncCedula = "707070707"
                        },
                        new
                        {
                            NCF = "E310000000009",
                            Itbis18 = 450.00m,
                            Monto = 2500.00m,
                            RncCedula = "707070707"
                        });
                });

            modelBuilder.Entity("Dgii.Domain.Entities.Taxpayer", b =>
                {
                    b.Property<string>("RncCedula")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("Estatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RncCedula");

                    b.ToTable("Taxpayers");

                    b.HasData(
                        new
                        {
                            RncCedula = "98754321012",
                            Estatus = "activo",
                            Nombre = "JUAN PEREZ",
                            Tipo = "PERSONA FISICA"
                        },
                        new
                        {
                            RncCedula = "123456789",
                            Estatus = "inactivo",
                            Nombre = "FARMACIA TU SALUD",
                            Tipo = "PERSONA JURIDICA"
                        },
                        new
                        {
                            RncCedula = "101010101",
                            Estatus = "activo",
                            Nombre = "SUPERMERCADOS NACIONAL",
                            Tipo = "PERSONA JURIDICA"
                        },
                        new
                        {
                            RncCedula = "202020202",
                            Estatus = "activo",
                            Nombre = "CLARO DOMINICANA",
                            Tipo = "PERSONA JURIDICA"
                        },
                        new
                        {
                            RncCedula = "303030303",
                            Estatus = "activo",
                            Nombre = "BANCO POPULAR DOMINICANO",
                            Tipo = "PERSONA JURIDICA"
                        },
                        new
                        {
                            RncCedula = "404040404",
                            Estatus = "activo",
                            Nombre = "MARIA GOMEZ",
                            Tipo = "PERSONA FISICA"
                        },
                        new
                        {
                            RncCedula = "505050505",
                            Estatus = "inactivo",
                            Nombre = "FERRETERIA AMERICANA",
                            Tipo = "PERSONA JURIDICA"
                        },
                        new
                        {
                            RncCedula = "606060606",
                            Estatus = "activo",
                            Nombre = "JOSE RODRIGUEZ",
                            Tipo = "PERSONA FISICA"
                        },
                        new
                        {
                            RncCedula = "707070707",
                            Estatus = "activo",
                            Nombre = "GRUPO RAMOS",
                            Tipo = "PERSONA JURIDICA"
                        },
                        new
                        {
                            RncCedula = "808080808",
                            Estatus = "inactivo",
                            Nombre = "ANA MARTINEZ",
                            Tipo = "PERSONA FISICA"
                        });
                });

            modelBuilder.Entity("Dgii.Domain.Entities.TaxReceipt", b =>
                {
                    b.HasOne("Dgii.Domain.Entities.Taxpayer", "Taxpayer")
                        .WithMany("TaxReceipts")
                        .HasForeignKey("RncCedula")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Taxpayer");
                });

            modelBuilder.Entity("Dgii.Domain.Entities.Taxpayer", b =>
                {
                    b.Navigation("TaxReceipts");
                });
#pragma warning restore 612, 618
        }
    }
}
